<?php
/** @var Magento\Framework\View\Element\Template $block */
?>

<h1>Vue SPA</h1>

<div id="vue-wrapper">
    <div id="vue-spa">Loading</div>
</div>

<script src="<?= $block->getViewFileUrl('Diko_VueSpa::js/app.js'); ?>" defer></script>
<script src="/vuespa/static/app-1.js" defer=""></script>
<script src="/vuespa/static/app-2.js" defer=""></script>
<!--
<script src="http://minio.local:81/vue-lic/app-1.js" defer=""></script>
-->
